### ISSUE TITLE
Question: login without selenium

### ISSUE THREAD

**Issue by maxperron** [JohnnyLin-a/lufa-weekly-canceler#1]
Hi! I recently forked your repository to create a simple API for Home Assistant to retrieve my delivery times. I'm currently attempting to replace Selenium to login based on POST requests, but I'm not getting anywhere. During your initial development of the script, did you explore this approach? Any insights or guidance you could offer would be greatly appreciated!

**Comment by JohnnyLin-a** [comment]
@maxperron Hi there! I took a bit of time to double check the login snippet.  
Looks like the only data needed is the `lufaState` cookie for your HTTP requests to be authenticated properly.
I have not touched this codebase in a long time so I could not tell exactly which endpoint it is, but it should be possible to use WireShark or the browser DevTools to check the network request stack and see which exact endpoint sets that cookie.

**Comment by maxperron** [comment]
Thanks, I think i found the endpoint, I just need to understand what to pass to obtain the cookie.
